(()=>{"use strict";
const C=document.querySelector("#game"),G=C.getContext("2d"),W=C.width,H=C.height,$=s=>document.querySelector(s);
const UI={score:$("#score"),stage:$("#stage"),lives:$("#lives"),combo:$("#combo"),best:$("#best"),shards:$("#shards"),objective:$("#objective"),rail:$("#powerRail"),boss:$("#bossHud"),bossBar:$("#bossBar"),bossName:$("#bossName"),toast:$("#toast")};
const KEY="arcaneRealmsV3",TODAY=new Date().toISOString().slice(0,10);
const DEFAULT={best:0,shards:0,unlocked:1,cleared:[],ach:[],stats:{bricks:0,bosses:0,powers:0,maxCombo:0,runs:0},up:{power:0,lives:0,wide:0,luck:0},skins:{paddles:["arcane"],balls:["aether"]},equipped:{paddle:"arcane",ball:"aether"},daily:{date:"",best:0,claimed:false},cfg:{sound:true,music:true,particles:true,shake:true}};
let S=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||"{}"));S.stats=Object.assign({},DEFAULT.stats,S.stats);S.up=Object.assign({},DEFAULT.up,S.up);S.skins=Object.assign({},DEFAULT.skins,S.skins);S.equipped=Object.assign({},DEFAULT.equipped,S.equipped);S.daily=Object.assign({},DEFAULT.daily,S.daily);S.cfg=Object.assign({},DEFAULT.cfg,S.cfg);
const REALMS=[
{name:"AETHER GARDENS",from:1,to:10,bg:["#071d32","#07101e","#02050b"],brick:["#10a8b9","#67e8f9"],accent:"#67e8f9",boss:"VERDANT SENTINEL"},
{name:"EMBER CITADEL",from:11,to:20,bg:["#32110c","#16090b","#050306"],brick:["#d85c24","#fbbf24"],accent:"#fb923c",boss:"INFERNO COLOSSUS"},
{name:"FROST MIRROR",from:21,to:30,bg:["#0b2140","#071323","#02050b"],brick:["#3b82f6","#bfdbfe"],accent:"#93c5fd",boss:"GLACIAL ORACLE"},
{name:"VOID TEMPLE",from:31,to:40,bg:["#21103b","#0c0718","#030207"],brick:["#7c3aed","#e879f9"],accent:"#c084fc",boss:"NULL ARCHON"},
{name:"CELESTIAL THRONE",from:41,to:50,bg:["#31250a","#13100a","#040403"],brick:["#ca8a04","#fde68a"],accent:"#fde68a",boss:"THE STAR KING"}];
const ACH=[
["first","FIRST SEAL","Clear your first stage",()=>S.cleared.length>=1,75],["breaker","SHATTERER","Break 500 bricks",()=>S.stats.bricks>=500,150],["combo","CHAIN WEAVER","Reach a 25-hit combo",()=>S.stats.maxCombo>=25,120],["boss","GIANT SLAYER","Defeat a realm guardian",()=>S.stats.bosses>=1,200],["boss5","KINGBREAKER","Defeat all five guardians",()=>S.stats.bosses>=5,600],["rich","SHARD HOARDER","Hold 1,000 shards",()=>S.shards>=1000,200],["power","RUNE ADDICT","Collect 100 power-ups",()=>S.stats.powers>=100,180],["realm","WAYFARER","Reach the Void Temple",()=>S.unlocked>=31,300],["finish","ASCENDANT","Clear stage 50",()=>S.cleared.includes(50),1000],["daily","RIFT WALKER","Complete a Daily Rift",()=>S.daily.claimed,200]];
const PADDLES={arcane:["Arcane","#22d3ee","#8b5cf6",0],ember:["Ember","#f97316","#fbbf24",350],frost:["Frost","#60a5fa","#e0f2fe",500],void:["Void","#8b5cf6","#f0abfc",700],royal:["Royal","#eab308","#fff7ae",1000]};
const BALLS={aether:["Aether","#cffafe","#0891b2",0],solar:["Solar","#fff7ae","#f97316",400],nova:["Nova","#f5d0fe","#7c3aed",600],frost:["Frost","#eff6ff","#3b82f6",750],star:["Star","#fff","#eab308",1200]};
const POW={wide:["WIDE",12000,"↔"],multi:["TRINITY",0,"×3"],laser:["LASER",12000,"ϟ"],slow:["CHRONO",9000,"◷"],shield:["AEGIS",16000,"◇"],fire:["INFERNO",10000,"✹"],magnet:["MAGNET",12000,"∩"],bomb:["NOVA",0,"✺"],life:["SOUL",0,"+1"],storm:["STORM",8000,"☄"],clone:["ECHO",0,"◎"]};
let state="menu",mode="journey",stage=S.unlocked,score=0,lives=3,combo=0,comboClock=0,last=0,shake=0,flash=0,bricks=[],balls=[],drops=[],shots=[],parts=[],hazards=[],boss=null,active={},keys={},nextShot=0,nextBossAttack=0,stageStart=0,deferredPrompt=null;
let paddle={x:400,y:1290,w:190,base:190,h:28,target:400};
const stars=Array.from({length:110},()=>({x:Math.random()*W,y:Math.random()*H,r:.3+Math.random()*1.8,a:.1+Math.random()*.5,s:.2+Math.random()}));
function realm(n=stage){return REALMS[Math.min(4,Math.floor((Math.max(1,n)-1)/10))]}
function persist(){localStorage.setItem(KEY,JSON.stringify(S));UI.best.textContent=S.best.toLocaleString();UI.shards.textContent=S.shards.toLocaleString()}
let AC,master,musicTimer;function tone(f=400,d=.05,type="sine",v=.035,slide=0){if(!S.cfg.sound)return;try{AC=AC||new(window.AudioContext||window.webkitAudioContext)();let o=AC.createOscillator(),g=AC.createGain();o.type=type;o.frequency.setValueAtTime(f,AC.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),AC.currentTime+d);g.gain.setValueAtTime(v,AC.currentTime);g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.connect(g).connect(AC.destination);o.start();o.stop(AC.currentTime+d)}catch(e){}}
function music(on=true){clearInterval(musicTimer);if(!on||!S.cfg.music)return;let seq=[110,165,220,196,147,220,247,165],i=0;musicTimer=setInterval(()=>{if(state==="play")tone(seq[i++%seq.length],.55,"sine",.009,20)},620)}
function toast(t,c="#67e8f9"){UI.toast.textContent=t;UI.toast.style.color=c;UI.toast.animate([{opacity:0,transform:"translate(-50%,-10px)"},{opacity:1,transform:"translate(-50%,0) scale(1.05)"},{opacity:0,transform:"translate(-50%,-20px)"}],{duration:1250})}
function checkAch(){for(let a of ACH)if(!S.ach.includes(a[0])&&a[3]()){S.ach.push(a[0]);S.shards+=a[4];toast("ACHIEVEMENT · "+a[1],"#fde68a");tone(880,.3,"sine",.05,300)}persist()}
function hud(){S.best=Math.max(S.best,score);UI.score.textContent=score.toLocaleString();UI.stage.textContent=mode==="daily"?"RIFT":stage;UI.lives.textContent=lives;UI.combo.textContent="×"+(1+Math.min(4,combo*.1)).toFixed(1);renderPowers();persist()}
function ball(stuck=true){let sp=610+Math.min(stage*10,140);return{x:paddle.x+paddle.w/2,y:paddle.y-18,r:11,vx:(Math.random()-.5)*210,vy:-sp,stuck,off:0,trail:[]}}
function patternKeep(r,c,rows,cols,n){let p=n%8;if(p===0)return true;if(p===1)return c>=Math.floor(r/2)&&c<cols-Math.floor(r/2);if(p===2)return (r+c)%2===0||r>rows-3;if(p===3)return Math.abs(c-(cols-1)/2)<=Math.max(1,4-r*.35)||r>rows-3;if(p===4)return r%2===0||c===0||c===cols-1;if(p===5)return Math.abs(c-(cols-1)/2)+Math.abs(r-rows/2)<6;if(p===6)return !(r>1&&r<rows-2&&c>2&&c<cols-3);return (c%3!==1)||r%3===0}
function addBrick(x,y,w,h,hp,type){bricks.push({x,y,w,h,hp,max:hp,type})}
function build(n){bricks=[];boss=null;hazards=[];let bossStage=mode!=="daily"&&n%10===0;UI.boss.classList.toggle("show",bossStage);let R=realm(n);UI.bossName.textContent=R.boss;UI.objective.textContent=mode==="daily"?"DAILY RIFT · ONE LIFE":bossStage?"DEFEAT "+R.boss:R.name+" · STAGE "+n;if(bossStage){boss={x:200,y:130,w:600,h:120,hp:55+n*3,max:55+n*3,vx:120+n*1.5,phase:0,type:Math.floor((n-1)/10)};for(let r=0;r<4;r++)for(let c=0;c<8;c++)if((r+c)%3)addBrick(95+c*103,330+r*59,92,42,r===0?2:1,"normal");return}
let rows=mode==="daily"?11:Math.min(7+Math.floor(n*.22),12),cols=10,gap=9,bw=(W-100-gap*9)/10,bh=42,seed=mode==="daily"?+TODAY.replaceAll("-",""):n;
for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){if(!patternKeep(r,c,rows,cols,seed))continue;let v=(Math.sin(seed*12.9898+r*78.233+c*37.719)*43758.5453)%1;v=Math.abs(v);let type=v<.055?"explosive":v<.11?"crystal":v<.17&&n>3?"steel":v<.205&&n>15?"phase":"normal",hp=type==="steel"?3:type==="crystal"?2:type==="phase"?2:1;addBrick(50+c*(bw+gap),145+r*(bh+gap),bw,bh,hp,type)}}
function begin(n=stage,daily=false){document.querySelectorAll(".overlay").forEach(x=>x.classList.remove("show"));mode=daily?"daily":"journey";stage=n;score=0;lives=daily?1:3+S.up.lives;S.stats.runs++;active={};paddle.base=190+S.up.wide*12;load();state="play";music(true);persist()}
function load(){combo=0;comboClock=0;drops=[];shots=[];parts=[];hazards=[];active={};paddle.w=paddle.base;paddle.x=W/2-paddle.w/2;paddle.target=paddle.x;build(stage);balls=[ball(true)];stageStart=performance.now();hud()}
function launch(){let ok=false;balls.forEach(b=>{if(b.stuck){b.stuck=false;b.vy=-Math.abs(b.vy);ok=true}});if(ok)tone(520,.08,"triangle",.04,120)}
function activate(k){S.stats.powers++;let now=performance.now();if(k==="multi"||k==="clone"){let extra=[];for(let b of [...balls])for(let a of(k==="clone"?[-.22]:[-.38,.38])){let sp=Math.hypot(b.vx,b.vy),ang=Math.atan2(b.vy,b.vx)+a;extra.push({...b,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,stuck:false,trail:[]})}balls.push(...extra)}else if(k==="life")lives++;else if(k==="bomb"){[...bricks].sort(()=>Math.random()-.5).slice(0,10).forEach(b=>damage(b,99,true));shake=20;flash=.7}else if(k==="storm"){active.storm=now+POW.storm[1]}else{active[k]=now+POW[k][1];if(k==="wide")paddle.w=paddle.base+105+S.up.wide*10}toast(POW[k][0]+" RUNE","#ffd166");tone(740,.15,"sine",.05,250);hud();checkAch()}
function renderPowers(){let now=performance.now(),s="";for(let k in active)if(active[k]>now){let p=POW[k][1]?((active[k]-now)/POW[k][1]*100):0;s+=`<span class="power"><b>${POW[k][2]} ${POW[k][0]}</b><i style="--p:${p}%"></i></span>`}UI.rail.innerHTML=s}
function expire(t){for(let k in active)if(active[k]<=t){delete active[k];if(k==="wide")paddle.w=paddle.base}}
function burst(x,y,col,n=14){if(!S.cfg.particles)return;for(let i=0;i<n;i++){let a=Math.random()*6.283,s=80+Math.random()*430;parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.4+Math.random()*.65,size:2+Math.random()*5,col,g:180+Math.random()*250})}}
function drop(b){let chance=.13+S.up.luck*.018;if(Math.random()>chance)return;let common=["wide","multi","laser","slow","shield","fire","magnet","bomb","life"],rare=["storm","clone"],k=Math.random()<.055+S.up.luck*.01?rare[Math.floor(Math.random()*rare.length)]:common[Math.floor(Math.random()*common.length)];drops.push({x:b.x+b.w/2,y:b.y+b.h/2,vy:190,k,spin:0})}
function damage(b,d=1,chain=false){if(!b||b.hp<=0)return;b.hp-=d;combo=Math.min(50,combo+1);S.stats.maxCombo=Math.max(S.stats.maxCombo,combo);comboClock=2.6;score+=Math.round(90*(1+Math.min(4,combo*.1))*(1+S.up.power*.04));burst(b.x+b.w/2,b.y+b.h/2,b.type==="explosive"?"#fb7185":realm().accent,12);shake=S.cfg.shake?Math.min(15,shake+3):0;tone(220+combo*7,.035,"square",.02,80);if(b.hp<=0){S.stats.bricks++;score+=140;drop(b);if(b.type==="explosive"&&!chain){let cx=b.x+b.w/2,cy=b.y+b.h/2;bricks.forEach(o=>{if(o!==b&&o.hp>0&&Math.hypot(o.x+o.w/2-cx,o.y+o.h/2-cy)<150)damage(o,2,true)});burst(cx,cy,"#fb7185",35);shake=18}}hud()}
function cc(o,r){let nx=Math.max(r.x,Math.min(o.x,r.x+r.w)),ny=Math.max(r.y,Math.min(o.y,r.y+r.h)),dx=o.x-nx,dy=o.y-ny;return dx*dx+dy*dy<o.r*o.r}
function hitBoss(b){if(!boss||!cc(b,boss))return false;boss.hp--;score+=220;combo++;comboClock=2.6;burst(b.x,b.y,"#e879f9",18);if(!active.fire)b.vy*=-1;UI.bossBar.style.width=boss.hp/boss.max*100+"%";tone(120,.07,"sawtooth",.04,100);if(boss.hp<=0){S.stats.bosses++;S.shards+=100+stage*5;score+=6000;toast("GUARDIAN DEFEATED","#f0abfc");burst(boss.x+boss.w/2,boss.y+boss.h/2,"#e879f9",100);boss=null;UI.boss.classList.remove("show");shake=25;flash=1;checkAch()}hud();return true}
function bossAI(dt,t){if(!boss)return;boss.x+=boss.vx*dt;if(boss.x<45||boss.x+boss.w>W-45)boss.vx*=-1;boss.phase+=dt;if(t<nextBossAttack)return;nextBossAttack=t+Math.max(850,1900-boss.type*180);let cx=boss.x+boss.w/2;if(boss.type===0)hazards.push({x:cx,y:boss.y+boss.h,vx:(paddle.x+paddle.w/2-cx)*.35,vy:300,r:12,type:"orb"});if(boss.type===1)for(let a of[-1,0,1])hazards.push({x:cx+a*80,y:boss.y+boss.h,vx:a*80,vy:330,r:13,type:"fire"});if(boss.type===2)hazards.push({x:paddle.x+paddle.w/2,y:boss.y+boss.h,vx:0,vy:420,r:15,type:"ice"});if(boss.type===3)for(let i=0;i<2;i++)hazards.push({x:100+Math.random()*800,y:boss.y+boss.h,vx:(Math.random()-.5)*150,vy:390,r:14,type:"void"});if(boss.type===4)for(let a=-2;a<=2;a++)hazards.push({x:cx,y:boss.y+boss.h,vx:a*95,vy:350,r:11,type:"star"});tone(85,.18,"sawtooth",.025,80)}
function step(dt,t){if(state!=="play")return;expire(t);if(comboClock>0&&(comboClock-=dt)<=0){combo=0;hud()}let sim=dt*(active.slow?.68:1);paddle.x+=(paddle.target-paddle.x)*Math.min(1,dt*15);if(keys.ArrowLeft||keys.a)paddle.target-=720*dt;if(keys.ArrowRight||keys.d)paddle.target+=720*dt;paddle.target=Math.max(0,Math.min(W-paddle.w,paddle.target));
if(active.laser&&t>nextShot){nextShot=t+330;shots.push({x:paddle.x+14,y:paddle.y,vy:-1050},{x:paddle.x+paddle.w-14,y:paddle.y,vy:-1050});tone(620,.03,"square",.014,150)}
if(active.storm&&Math.floor(t/180)!==Math.floor((t-dt*1000)/180)){let live=bricks.filter(b=>b.hp>0);if(live.length)damage(live[Math.floor(Math.random()*live.length)],1,true)}
shots.forEach(s=>s.y+=s.vy*dt);for(let s of shots)for(let b of bricks)if(!s.dead&&b.hp>0&&s.x>b.x&&s.x<b.x+b.w&&s.y>b.y&&s.y<b.y+b.h){damage(b);s.dead=1}shots=shots.filter(s=>!s.dead&&s.y>-30);bossAI(dt,t);
for(let h of hazards){h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.y>paddle.y-10&&h.y<paddle.y+paddle.h+25&&h.x>paddle.x&&h.x<paddle.x+paddle.w){h.dead=1;if(active.shield){delete active.shield;toast("AEGIS BLOCK","#86efac")}else{lives--;shake=18;toast("GUARDIAN STRIKE","#fb7185");tone(80,.25,"sawtooth",.05,-30);if(lives<=0)return gameOver()}hud()}}hazards=hazards.filter(h=>!h.dead&&h.y<H+40);
for(let b of balls){if(b.stuck){b.x=paddle.x+paddle.w/2+b.off;b.y=paddle.y-b.r-2;continue}b.trail.push({x:b.x,y:b.y});if(b.trail.length>14)b.trail.shift();b.x+=b.vx*sim;b.y+=b.vy*sim;if(b.x<b.r){b.x=b.r;b.vx=Math.abs(b.vx)}if(b.x>W-b.r){b.x=W-b.r;b.vx=-Math.abs(b.vx)}if(b.y<b.r){b.y=b.r;b.vy=Math.abs(b.vy)}
if(b.vy>0&&cc(b,paddle)){b.y=paddle.y-b.r;let rel=(b.x-(paddle.x+paddle.w/2))/(paddle.w/2),sp=Math.min(950,Math.max(590,Math.hypot(b.vx,b.vy)*1.012));b.vx=rel*sp*.9;b.vy=-Math.sqrt(Math.max(130000,sp*sp-b.vx*b.vx));if(active.magnet){b.stuck=true;b.off=Math.max(-paddle.w*.4,Math.min(paddle.w*.4,b.x-(paddle.x+paddle.w/2)))}tone(330,.045,"triangle",.025,70)}
if(hitBoss(b))continue;for(let br of bricks){if(br.hp<=0||!cc(b,br))continue;damage(br);if(!active.fire){let cx=b.x-(br.x+br.w/2),cy=b.y-(br.y+br.h/2);if(Math.abs(cx/br.w)>Math.abs(cy/br.h))b.vx*=-1;else b.vy*=-1}break}
if(b.y>H+35&&active.shield){b.y=H-60;b.vy=-Math.abs(b.vy);delete active.shield;toast("AEGIS CONSUMED","#86efac")}}
balls=balls.filter(b=>b.y<H+70);drops.forEach(d=>{d.y+=d.vy*dt;d.spin+=dt*4;if(d.y>paddle.y-12&&d.y<paddle.y+paddle.h+35&&d.x>paddle.x&&d.x<paddle.x+paddle.w){activate(d.k);d.dead=1}});drops=drops.filter(d=>!d.dead&&d.y<H+50);parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.g*dt;p.life-=dt});parts=parts.filter(p=>p.life>0);bricks=bricks.filter(b=>b.hp>0);
if(!balls.length){lives--;if(lives<=0)return gameOver();balls=[ball(true)];combo=0;toast("SOUL FRACTURED","#fb7185");hud()}
if(!bricks.length&&!boss){state="transition";clearStage();}}
function clearStage(){let reward=mode==="daily"?0:35+stage*3;score+=1200+stage*180;if(mode==="daily"){if(score>S.daily.best)S.daily.best=score;if(!S.daily.claimed||S.daily.date!==TODAY){S.daily={date:TODAY,best:score,claimed:true};S.shards+=250;toast("DAILY RIFT COMPLETE · +250","#fde68a")}persist();checkAch();setTimeout(()=>{state="menu";openMenu()},1000);return}
if(!S.cleared.includes(stage)){S.cleared.push(stage);S.shards+=reward}S.unlocked=Math.max(S.unlocked,Math.min(50,stage+1));persist();checkAch();toast("STAGE PURIFIED · +"+reward+" ✦","#a7f3d0");setTimeout(()=>{if(stage>=50){state="menu";openMenu()}else{stage++;load();state="play"}},1050)}
function gameOver(){state="over";music(false);$("#endTitle").textContent=mode==="daily"?"RIFT CLOSED":"THE RIFT CLAIMS YOU";$("#endText").textContent=`Score ${score.toLocaleString()} · ${mode==="daily"?"Daily Rift":"Stage "+stage} · Best ${S.best.toLocaleString()}`;$("#end").classList.add("show");persist()}
function rr(x,y,w,h,r){G.beginPath();G.roundRect(x,y,w,h,r);G.fill()}
function draw(t){let R=realm(),sx=shake?(Math.random()-.5)*shake:0,sy=shake?(Math.random()-.5)*shake:0;shake*=.86;G.save();G.translate(sx,sy);G.clearRect(-30,-30,W+60,H+60);let bg=G.createLinearGradient(0,0,0,H);R.bg.forEach((c,i)=>bg.addColorStop(i/(R.bg.length-1),c));G.fillStyle=bg;G.fillRect(0,0,W,H);stars.forEach(s=>{G.globalAlpha=s.a*(.7+.3*Math.sin(t*.001*s.s+s.x));G.fillStyle=R.accent;G.beginPath();G.arc(s.x,s.y,s.r,0,7);G.fill()});G.globalAlpha=1;G.strokeStyle=R.accent+"18";for(let x=0;x<W;x+=50){G.beginPath();G.moveTo(x,0);G.lineTo(x,H);G.stroke()}for(let y=0;y<H;y+=50){G.beginPath();G.moveTo(0,y);G.lineTo(W,y);G.stroke()}
bricks.forEach(b=>{let col=b.type==="steel"?"#718096":b.type==="crystal"?"#8b5cf6":b.type==="explosive"?"#e64d6c":b.type==="phase"?"#e879f9":R.brick[0];G.shadowBlur=13;G.shadowColor=col;let gr=G.createLinearGradient(b.x,b.y,b.x,b.y+b.h);gr.addColorStop(0,col);gr.addColorStop(1,"#07101b");G.fillStyle=gr;rr(b.x,b.y,b.w,b.h,8);G.shadowBlur=0;G.fillStyle="#ffffff22";rr(b.x+4,b.y+4,b.w-8,7,3);if(b.type==="explosive"||b.type==="crystal"||b.type==="phase"){G.fillStyle="#fff";G.font="16px serif";G.textAlign="center";G.fillText(b.type==="explosive"?"✹":b.type==="crystal"?"◆":"◈",b.x+b.w/2,b.y+28)}});
if(boss){G.shadowBlur=35;G.shadowColor=R.accent;let gr=G.createLinearGradient(boss.x,boss.y,boss.x+boss.w,boss.y);gr.addColorStop(0,R.brick[0]);gr.addColorStop(.5,R.brick[1]);gr.addColorStop(1,R.brick[0]);G.fillStyle=gr;rr(boss.x,boss.y,boss.w,boss.h,30);G.shadowBlur=0;G.fillStyle="#fff";G.font="36px serif";G.textAlign="center";G.fillText(["❈  ◇  ❈","✹  ◉  ✹","❄  ◇  ❄","◈  ●  ◈","✦  ♛  ✦"][boss.type],boss.x+boss.w/2,boss.y+72)}
let pc=PADDLES[S.equipped.paddle]||PADDLES.arcane,bc=BALLS[S.equipped.ball]||BALLS.aether;for(let b of balls){b.trail.forEach((q,i)=>{G.globalAlpha=i/b.trail.length*.25;G.fillStyle=active.fire?"#fb923c":bc[1];G.beginPath();G.arc(q.x,q.y,b.r*i/b.trail.length,0,7);G.fill()});G.globalAlpha=1;G.shadowBlur=28;G.shadowColor=active.fire?"#f97316":bc[2];let og=G.createRadialGradient(b.x-3,b.y-3,1,b.x,b.y,b.r);og.addColorStop(0,"#fff");og.addColorStop(.45,bc[1]);og.addColorStop(1,bc[2]);G.fillStyle=og;G.beginPath();G.arc(b.x,b.y,b.r,0,7);G.fill();G.shadowBlur=0}
G.shadowBlur=25;G.shadowColor=pc[1];let pg=G.createLinearGradient(paddle.x,0,paddle.x+paddle.w,0);pg.addColorStop(0,pc[1]);pg.addColorStop(.5,"#fff");pg.addColorStop(1,pc[2]);G.fillStyle=pg;rr(paddle.x,paddle.y,paddle.w,paddle.h,14);G.shadowBlur=0;
const gl={wide:"↔",multi:"×3",laser:"ϟ",slow:"◷",shield:"◇",fire:"✹",magnet:"∩",bomb:"✺",life:"+1",storm:"☄",clone:"◎"};drops.forEach(d=>{G.save();G.translate(d.x,d.y);G.rotate(Math.sin(d.spin)*.15);G.shadowBlur=18;G.shadowColor=d.k==="storm"||d.k==="clone"?"#f0abfc":"#ffd166";G.fillStyle="#0b1425";G.strokeStyle=d.k==="storm"||d.k==="clone"?"#f0abfc":"#ffd166";G.lineWidth=3;G.beginPath();G.arc(0,0,23,0,7);G.fill();G.stroke();G.shadowBlur=0;G.fillStyle="#fff";G.font="bold 13px sans-serif";G.textAlign="center";G.fillText(gl[d.k],0,5);G.restore()});
G.strokeStyle="#fb7185";G.lineWidth=5;shots.forEach(s=>{G.beginPath();G.moveTo(s.x,s.y);G.lineTo(s.x,s.y+22);G.stroke()});hazards.forEach(h=>{G.shadowBlur=18;G.shadowColor="#fb7185";G.fillStyle="#fecdd3";G.beginPath();G.arc(h.x,h.y,h.r,0,7);G.fill();G.shadowBlur=0});parts.forEach(p=>{G.globalAlpha=Math.max(0,p.life);G.fillStyle=p.col;G.fillRect(p.x,p.y,p.size,p.size)});G.globalAlpha=1;if(balls.some(b=>b.stuck)&&state==="play"){G.fillStyle="#dbeafeaa";G.font="800 19px sans-serif";G.textAlign="center";G.fillText(active.magnet?"TAP TO RELEASE":"TAP / SPACE TO LAUNCH",W/2,1195)}if(flash>0){G.globalAlpha=flash;G.fillStyle="#fff";G.fillRect(0,0,W,H);G.globalAlpha=1;flash=Math.max(0,flash-.08)}G.restore()}
function loop(t){let dt=Math.min(.025,(t-last)/1000||0);last=t;step(dt,t);draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function modal(html){$("#modalContent").innerHTML=html;$("#modal").classList.add("show")}
function mapView(){let cards=REALMS.map((r,i)=>`<div class="realmCard"><b>${i+1}. ${r.name}</b><span>Stages ${r.from}–${r.to} · Guardian: ${r.boss}</span></div>`).join("");let nodes="";for(let i=1;i<=50;i++)nodes+=`<button class="node ${S.cleared.includes(i)?"done":""} ${i===S.unlocked?"current":""} ${i%10===0?"boss":""}" data-stage="${i}" ${i>S.unlocked?"disabled":""}>${i}</button>`;modal(`<p class="eyebrow">JOURNEY</p><h2>REALM MAP</h2>${cards}<div class="map">${nodes}</div>`);document.querySelectorAll("[data-stage]").forEach(b=>b.onclick=()=>begin(+b.dataset.stage,false))}
function forge(){let up=[["power","ARCANE FORCE","Score +4% per rank",100],["lives","SOUL VESSEL","+1 starting life",250],["wide","PADDLE MASTERY","Wider permanent paddle",160],["luck","RUNE FORTUNE","Better power-up drop rate",180]].map(x=>{let lv=S.up[x[0]],cost=x[3]*(lv+1);return `<div class="shoprow"><div><b>${x[1]} · Lv ${lv}/5</b><small>${x[2]}</small></div><button data-up="${x[0]}" data-cost="${cost}" ${lv>=5||S.shards<cost?"disabled":""}>${lv>=5?"MAX":cost+" ✦"}</button></div>`}).join("");let pads=Object.entries(PADDLES).map(([k,v])=>`<button class="skin ${S.equipped.paddle===k?"active":""}" data-pad="${k}" data-cost="${v[3]}" ${!S.skins.paddles.includes(k)&&S.shards<v[3]?"disabled":""}>${v[0]}<br><small>${S.skins.paddles.includes(k)?"OWNED":v[3]+" ✦"}</small></button>`).join("");let bs=Object.entries(BALLS).map(([k,v])=>`<button class="skin ${S.equipped.ball===k?"active":""}" data-ball="${k}" data-cost="${v[3]}" ${!S.skins.balls.includes(k)&&S.shards<v[3]?"disabled":""}>${v[0]}<br><small>${S.skins.balls.includes(k)?"OWNED":v[3]+" ✦"}</small></button>`).join("");modal(`<p class="eyebrow">PERMANENT PROGRESSION · ${S.shards} ✦</p><h2>ARCANE FORGE</h2>${up}<h3>PADDLES</h3><div class="skinGrid">${pads}</div><h3>ORBS</h3><div class="skinGrid">${bs}</div>`);document.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>{let k=b.dataset.up,c=+b.dataset.cost;if(S.shards>=c&&S.up[k]<5){S.shards-=c;S.up[k]++;persist();forge()}});document.querySelectorAll("[data-pad]").forEach(b=>b.onclick=()=>buySkin("paddles","paddle",b.dataset.pad,+b.dataset.cost,PADDLES));document.querySelectorAll("[data-ball]").forEach(b=>b.onclick=()=>buySkin("balls","ball",b.dataset.ball,+b.dataset.cost,BALLS))}
function buySkin(list,equip,k,c,obj){if(!S.skins[list].includes(k)){if(S.shards<c)return;S.shards-=c;S.skins[list].push(k)}S.equipped[equip]=k;persist();forge()}
function achievements(){checkAch();modal(`<p class="eyebrow">${S.ach.length}/${ACH.length} UNLOCKED</p><h2>ACHIEVEMENTS</h2>`+ACH.map(a=>`<div class="achrow"><div><b>${S.ach.includes(a[0])?"✓ ":""}${a[1]}</b><small>${a[2]}</small></div><span>${a[4]} ✦</span></div>`).join(""))}
function daily(){let done=S.daily.date===TODAY&&S.daily.claimed;modal(`<p class="eyebrow">${TODAY}</p><h2>DAILY RIFT</h2><p>A deterministic challenge shared by today's date. One life. Rare runes enabled. First completion today awards <b>250 shards</b>.</p><p>Today's best: <b>${S.daily.date===TODAY?S.daily.best.toLocaleString():0}</b></p><button id="startDaily" class="primary">${done?"PLAY AGAIN":"ENTER DAILY RIFT"}</button>`);$("#startDaily").onclick=()=>begin(25,true)}
function settings(){modal(`<h2>SETTINGS</h2>`+["sound","music","particles","shake"].map(k=>`<label class="setting"><span>${k.toUpperCase()}</span><input type="checkbox" data-cfg="${k}" ${S.cfg[k]?"checked":""}></label>`).join("")+`<p>Progress, purchases, achievements and daily score are saved on this device.</p>`);document.querySelectorAll("[data-cfg]").forEach(i=>i.onchange=()=>{S.cfg[i.dataset.cfg]=i.checked;persist();if(i.dataset.cfg==="music")music(i.checked)})}
function openMenu(){document.querySelectorAll(".overlay").forEach(x=>x.classList.remove("show"));$("#menu").classList.add("show");state="menu";music(false);hud()}
$("#continue").onclick=()=>begin(S.unlocked,false);$("#mapBtn").onclick=mapView;$("#shopBtn").onclick=forge;$("#achBtn").onclick=achievements;$("#dailyBtn").onclick=daily;$("#settings").onclick=settings;$("#closeModal").onclick=()=>$("#modal").classList.remove("show");$("#again").onclick=openMenu;$("#quit").onclick=openMenu;
function pause(){if(state==="play"){state="pause";$("#pause").classList.add("show")}else if(state==="pause"){state="play";$("#pause").classList.remove("show")}}$("#pauseBtn").onclick=pause;$("#resume").onclick=pause;$("#restart").onclick=()=>{load();$("#pause").classList.remove("show");state="play"};document.querySelectorAll(".settingsOpen").forEach(b=>b.onclick=settings);
addEventListener("keydown",e=>{keys[e.key]=true;if(e.key===" "){e.preventDefault();launch()}if((e.key.toLowerCase()==="p"||e.key==="Escape")&&!$("#modal").classList.contains("show"))pause()});addEventListener("keyup",e=>keys[e.key]=false);function px(e){let r=C.getBoundingClientRect();return(e.clientX-r.left)/r.width*W}C.addEventListener("pointermove",e=>{if(state==="play")paddle.target=px(e)-paddle.w/2});C.addEventListener("pointerdown",e=>{if(state==="play"){paddle.target=px(e)-paddle.w/2;launch()}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").hidden=true}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
persist();checkAch();hud();
})();