(()=>{"use strict";
const C=document.querySelector("#game"),G=C.getContext("2d"),W=C.width,H=C.height,$=s=>document.querySelector(s);
const E={score:$("#score"),stage:$("#stage"),lives:$("#lives"),combo:$("#combo"),best:$("#best"),objective:$("#objective"),rail:$("#powerRail"),boss:$("#bossHud"),bossBar:$("#bossBar"),toast:$("#toast")};
const SAVE="arcaneAscensionV2"; let save=JSON.parse(localStorage.getItem(SAVE)||"{}");
let cfg=Object.assign({sound:true,particles:true,shake:true,reduced:false},save.cfg||{}),best=save.best||0;
let state="menu",score=0,stage=1,lives=3,combo=0,comboClock=0,last=0,screenShake=0,flash=0,stars=[],dust=[],bricks=[],balls=[],drops=[],shots=[],parts=[],boss=null,stageClear=false,keys={},nextShot=0;
let paddle={x:400,y:1290,w:190,baseW:190,h:28,target:400,magnet:false};
const POW={wide:{name:"WIDE",dur:12000,glyph:"↔"},laser:{name:"LASER",dur:12000,glyph:"ϟ"},slow:{name:"CHRONO",dur:9000,glyph:"◷"},shield:{name:"AEGIS",dur:16000,glyph:"◇"},fire:{name:"INFERNO",dur:10000,glyph:"✹"},magnet:{name:"MAGNET",dur:12000,glyph:"∩"}};
let active={};
for(let i=0;i<105;i++)stars.push({x:Math.random()*W,y:Math.random()*H,r:.4+Math.random()*1.8,a:.12+Math.random()*.5,s:.15+Math.random()*.45});
for(let i=0;i<18;i++)dust.push({x:Math.random()*W,y:Math.random()*H,r:8+Math.random()*25,a:.015+Math.random()*.035});
let AC;function sfx(f=400,d=.05,type="sine",v=.035,slide=0){if(!cfg.sound)return;try{AC=AC||new (window.AudioContext||window.webkitAudioContext)();let o=AC.createOscillator(),g=AC.createGain();o.type=type;o.frequency.setValueAtTime(f,AC.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),AC.currentTime+d);g.gain.setValueAtTime(v,AC.currentTime);g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+d);o.connect(g).connect(AC.destination);o.start();o.stop(AC.currentTime+d)}catch(e){}}
function chord(win=true){[0,100,200].forEach((q,i)=>setTimeout(()=>sfx((win?440:150)*(1+i*.25),.14,"sine",.035,win?120:-50),q))}
function toast(t,c="#73efff"){E.toast.textContent=t;E.toast.style.color=c;E.toast.animate([{opacity:0,transform:"translate(-50%,-12px) scale(.9)"},{opacity:1,transform:"translate(-50%,0) scale(1.05)"},{opacity:0,transform:"translate(-50%,-20px) scale(1)"}],{duration:1250,easing:"ease-out"})}
function saveGame(){best=Math.max(best,score);localStorage.setItem(SAVE,JSON.stringify({best,cfg}));E.best.textContent=best.toLocaleString()}
function hud(){E.score.textContent=score.toLocaleString();E.stage.textContent=stage;E.lives.textContent=lives;let mult=1+Math.min(4,combo*.1);E.combo.textContent="×"+mult.toFixed(1);saveGame();renderPowers()}
function mult(){return 1+Math.min(4,combo*.1)}
function ball(stuck=true){let speed=610+Math.min(stage*16,150);return{x:paddle.x+paddle.w/2,y:paddle.y-18,r:11,vx:(Math.random()-.5)*220,vy:-speed,stuck,stuckOffset:0,trail:[],ghost:0}}
function newRun(){score=0;stage=1;lives=3;active={};paddle.w=paddle.baseW;loadStage()}
function loadStage(){combo=0;comboClock=0;drops=[];shots=[];parts=[];stageClear=false;paddle.w=paddle.baseW;paddle.x=W/2-paddle.w/2;paddle.target=paddle.x;active={};boss=null;buildStage();balls=[ball(true)];hud()}
function buildStage(){bricks=[];let bossStage=stage%5===0;E.boss.classList.toggle("show",bossStage);E.objective.textContent=bossStage?"DEFEAT THE ARCANE WARDEN":"CLEAR THE VAULT";if(bossStage){boss={x:220,y:135,w:560,h:115,hp:35+stage*5,max:35+stage*5,vx:115+stage*3,phase:0};for(let r=0;r<4;r++)for(let c=0;c<8;c++)if((r+c)%3!==0)addBrick(95+c*103,320+r*60,92,44,r===0?2:1,"normal");return}
let rows=Math.min(7+Math.floor(stage*.65),12),cols=10,gap=9,bw=(W-100-gap*(cols-1))/cols,bh=43;
for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){let pattern=stage%4,keep=true;if(pattern===1)keep=(c>=r/2&&c<cols-r/2)||(r>4);if(pattern===2)keep=(r+c)%2===0||r>rows-3;if(pattern===3)keep=Math.abs(c-4.5)<=Math.max(1,4-r*.35)||r>rows-3;if(!keep)continue;let roll=Math.random(),type=roll<.055?"explosive":roll<.11?"crystal":roll<.17&&stage>2?"steel":"normal",hp=type==="steel"?3:type==="crystal"?2:1;if(stage>4&&r===0&&type==="normal")hp=2;addBrick(50+c*(bw+gap),145+r*(bh+gap),bw,bh,hp,type)}}
function addBrick(x,y,w,h,hp,type){bricks.push({x,y,w,h,hp,max:hp,type,pulse:Math.random()*7})}
function launch(){let did=false;balls.forEach(b=>{if(b.stuck){b.stuck=false;b.vy=-Math.abs(b.vy);did=true}});if(did)sfx(520,.09,"triangle",.04,120)}
function activate(type){let now=performance.now();if(type==="multi"){let base=[...balls],extra=[];base.forEach(b=>{[-.38,.38].forEach(a=>{let sp=Math.hypot(b.vx,b.vy),ang=Math.atan2(b.vy,b.vx)+a;extra.push({...b,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,stuck:false,trail:[]})})});balls.push(...extra);toast("TRINITY ORB","#c4b5fd")}
else if(type==="life"){lives++;toast("SOUL RESTORED","#86efac")}
else if(type==="bomb"){toast("NOVA BLAST","#fda4af");let targets=bricks.filter(b=>b.hp>0).sort(()=>Math.random()-.5).slice(0,8);targets.forEach(b=>damageBrick(b,null,99,true));screenShake=18;flash=.8}
else{active[type]=now+POW[type].dur;if(type==="wide")paddle.w=300;if(type==="magnet")paddle.magnet=true;toast(POW[type].name+" RUNE","#ffd166")}hud();sfx(740,.16,"sine",.055,240)}
function renderPowers(){let now=performance.now(),out="";Object.keys(active).forEach(k=>{if(active[k]<=now)return;let p=Math.max(0,(active[k]-now)/POW[k].dur*100);out+=`<span class="power"><b>${POW[k].glyph} ${POW[k].name}</b><i style="--p:${p}%"></i></span>`});E.rail.innerHTML=out}
function expire(t){Object.keys(active).forEach(k=>{if(active[k]>t)return;delete active[k];if(k==="wide")paddle.w=paddle.baseW;if(k==="magnet")paddle.magnet=false});renderPowers()}
function burst(x,y,col="#67e8f9",n=14){if(!cfg.particles)return;for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=80+Math.random()*430;parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.4+Math.random()*.65,max:1,size:2+Math.random()*5,col,grav:180+Math.random()*260})}}
function dropFrom(b){let chance=.16;if(Math.random()>chance)return;let bag=["wide","multi","laser","slow","shield","fire","magnet","bomb","life"],weights=[16,14,12,12,11,10,10,8,7],r=Math.random()*weights.reduce((a,v)=>a+v,0),type=bag[0];for(let i=0;i<bag.length;i++){r-=weights[i];if(r<=0){type=bag[i];break}}drops.push({x:b.x+b.w/2,y:b.y+b.h/2,vy:190,type,spin:Math.random()*5})}
function damageBrick(b,ball,dmg=1,chain=false){if(!b||b.hp<=0)return;b.hp-=dmg;combo=Math.min(40,combo+1);comboClock=2.5;score+=Math.round(90*mult());let col=b.type==="steel"?"#cbd5e1":b.type==="crystal"?"#c084fc":b.type==="explosive"?"#fb7185":"#67e8f9";burst(b.x+b.w/2,b.y+b.h/2,col,12);screenShake=cfg.shake?Math.min(16,screenShake+3):0;sfx(210+combo*8,.035,"square",.022,80);
if(b.hp<=0){score+=Math.round(140*mult());dropFrom(b);if(b.type==="explosive"&&!chain){let cx=b.x+b.w/2,cy=b.y+b.h/2;bricks.forEach(o=>{if(o!==b&&o.hp>0&&Math.hypot(o.x+o.w/2-cx,o.y+o.h/2-cy)<150)damageBrick(o,null,2,true)});burst(cx,cy,"#fb7185",35);screenShake=18;sfx(95,.22,"sawtooth",.06,-40)}}hud()}
function collideCircleRect(o,r){let nx=Math.max(r.x,Math.min(o.x,r.x+r.w)),ny=Math.max(r.y,Math.min(o.y,r.y+r.h)),dx=o.x-nx,dy=o.y-ny;return dx*dx+dy*dy<o.r*o.r}
function bossHit(ball){if(!boss||boss.hp<=0||!collideCircleRect(ball,boss))return false;boss.hp--;score+=Math.round(250*mult());combo++;comboClock=2.5;burst(ball.x,ball.y,"#e879f9",18);screenShake=8;let cy=ball.y-(boss.y+boss.h/2),cx=ball.x-(boss.x+boss.w/2);if(!active.fire){if(Math.abs(cx/boss.w)>Math.abs(cy/boss.h))ball.vx*=-1;else ball.vy*=-1}E.bossBar.style.width=(boss.hp/boss.max*100)+"%";sfx(120,.08,"sawtooth",.04,100);if(boss.hp<=0){score+=5000;toast("WARDEN SHATTERED","#f0abfc");burst(boss.x+boss.w/2,boss.y+boss.h/2,"#e879f9",90);boss=null;E.boss.classList.remove("show");screenShake=25;flash=1;chord(true)}hud();return true}
function step(dt,t){if(state!=="play")return;expire(t);if(comboClock>0){comboClock-=dt;if(comboClock<=0){combo=0;hud()}}
let slow=active.slow>t?.68:1,sim=dt*slow;paddle.x+=(paddle.target-paddle.x)*Math.min(1,dt*15);if(keys.ArrowLeft||keys.a)paddle.target-=720*dt;if(keys.ArrowRight||keys.d)paddle.target+=720*dt;paddle.target=Math.max(0,Math.min(W-paddle.w,paddle.target));
if(active.laser>t&&t>nextShot){nextShot=t+330;shots.push({x:paddle.x+15,y:paddle.y,vy:-1050},{x:paddle.x+paddle.w-15,y:paddle.y,vy:-1050});sfx(620,.035,"square",.018,160)}
shots.forEach(s=>s.y+=s.vy*dt);for(let s of shots){for(let b of bricks){if(b.hp>0&&s.x>b.x&&s.x<b.x+b.w&&s.y>b.y&&s.y<b.y+b.h){damageBrick(b,null);s.dead=1;break}}if(boss&&s.x>boss.x&&s.x<boss.x+boss.w&&s.y>boss.y&&s.y<boss.y+boss.h){boss.hp--;E.bossBar.style.width=(boss.hp/boss.max*100)+"%";s.dead=1}}shots=shots.filter(s=>!s.dead&&s.y>-40);
if(boss){boss.x+=boss.vx*dt;if(boss.x<55||boss.x+boss.w>W-55)boss.vx*=-1;boss.phase+=dt}
for(let b of balls){if(b.stuck){b.x=paddle.x+paddle.w/2+b.stuckOffset;b.y=paddle.y-b.r-2;continue}b.trail.push({x:b.x,y:b.y});if(b.trail.length>14)b.trail.shift();b.x+=b.vx*sim;b.y+=b.vy*sim;
if(b.x<b.r){b.x=b.r;b.vx=Math.abs(b.vx);sfx(170,.025)}if(b.x>W-b.r){b.x=W-b.r;b.vx=-Math.abs(b.vx);sfx(170,.025)}if(b.y<b.r){b.y=b.r;b.vy=Math.abs(b.vy);sfx(170,.025)}
if(b.vy>0&&collideCircleRect(b,paddle)){b.y=paddle.y-b.r;let rel=(b.x-(paddle.x+paddle.w/2))/(paddle.w/2),sp=Math.min(930,Math.max(590,Math.hypot(b.vx,b.vy)*1.012));b.vx=rel*sp*.9;b.vy=-Math.sqrt(Math.max(130000,sp*sp-b.vx*b.vx));if(active.magnet>t){b.stuck=true;b.stuckOffset=Math.max(-paddle.w*.4,Math.min(paddle.w*.4,b.x-(paddle.x+paddle.w/2)))}sfx(330,.05,"triangle",.03,80)}
if(bossHit(b))continue;
for(let br of bricks){if(br.hp<=0||!collideCircleRect(b,br))continue;damageBrick(br,b);if(!active.fire){let cx=b.x-(br.x+br.w/2),cy=b.y-(br.y+br.h/2);if(Math.abs(cx/br.w)>Math.abs(cy/br.h))b.vx*=-1;else b.vy*=-1}else b.vy*=1.001;break}
if(b.y>H+35&&active.shield>t){b.y=H-55;b.vy=-Math.abs(b.vy);delete active.shield;toast("AEGIS CONSUMED","#86efac");burst(b.x,H-30,"#86efac",30);sfx(130,.18,"sawtooth",.05,180)}}
balls=balls.filter(b=>b.y<H+70);
for(let d of drops){d.y+=d.vy*dt;d.spin+=dt*4;if(d.y>paddle.y-12&&d.y<paddle.y+paddle.h+35&&d.x>paddle.x&&d.x<paddle.x+paddle.w){activate(d.type);d.dead=1}}drops=drops.filter(d=>!d.dead&&d.y<H+50);
parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.grav*dt;p.life-=dt});parts=parts.filter(p=>p.life>0);
bricks=bricks.filter(b=>b.hp>0);
if(!bricks.length&&!boss&&!stageClear){stageClear=true;state="transition";score+=1000+stage*250;hud();toast("STAGE "+stage+" PURIFIED","#a7f3d0");chord(true);setTimeout(()=>{stage++;loadStage();state="play"},1100)}
if(!balls.length&&state==="play"){lives--;combo=0;if(lives<=0){state="over";$("#endTitle").textContent="THE VAULT ENDURES";$("#endText").textContent=`Score ${score.toLocaleString()} · Stage ${stage} · Best ${Math.max(best,score).toLocaleString()}`;$("#end").classList.add("show");chord(false)}else{balls=[ball(true)];toast("SOUL FRACTURED","#fb7185");sfx(100,.3,"sawtooth",.05,-40)}hud()}}
function roundRect(x,y,w,h,r){G.beginPath();G.roundRect(x,y,w,h,r);G.fill()}
function draw(t){let sx=screenShake?(Math.random()-.5)*screenShake:0,sy=screenShake?(Math.random()-.5)*screenShake:0;screenShake*=.86;G.save();G.translate(sx,sy);G.clearRect(-30,-30,W+60,H+60);
let bg=G.createLinearGradient(0,0,0,H);bg.addColorStop(0,"#071a32");bg.addColorStop(.45,"#080b20");bg.addColorStop(1,"#02040b");G.fillStyle=bg;G.fillRect(0,0,W,H);
dust.forEach(d=>{G.globalAlpha=d.a*(1+Math.sin(t*.0005+d.x)*.4);G.fillStyle="#60a5fa";G.beginPath();G.arc(d.x,d.y,d.r,0,7);G.fill()});stars.forEach(s=>{G.globalAlpha=s.a*(.7+.3*Math.sin(t*.001*s.s+s.x));G.fillStyle="#e0f2fe";G.beginPath();G.arc(s.x,s.y,s.r,0,7);G.fill()});G.globalAlpha=1;
let vg=G.createRadialGradient(W/2,H*.45,120,W/2,H*.45,760);vg.addColorStop(0,"#0ea5e90a");vg.addColorStop(1,"#00000066");G.fillStyle=vg;G.fillRect(0,0,W,H);
G.strokeStyle="#16355735";G.lineWidth=1;for(let x=0;x<W;x+=50){G.beginPath();G.moveTo(x,0);G.lineTo(x,H);G.stroke()}for(let y=0;y<H;y+=50){G.beginPath();G.moveTo(0,y);G.lineTo(W,y);G.stroke()}
bricks.forEach(b=>{let col=b.type==="steel"?"#718096":b.type==="crystal"?"#8b5cf6":b.type==="explosive"?"#e64d6c":b.hp>1?"#168ec0":"#087b9b";G.shadowBlur=14;G.shadowColor=col;let gr=G.createLinearGradient(b.x,b.y,b.x,b.y+b.h);gr.addColorStop(0,col);gr.addColorStop(1,"#071827");G.fillStyle=gr;roundRect(b.x,b.y,b.w,b.h,8);G.shadowBlur=0;G.fillStyle="#ffffff20";roundRect(b.x+4,b.y+4,b.w-8,7,4);G.strokeStyle="#ffffff25";G.strokeRect(b.x+5,b.y+5,b.w-10,b.h-10);if(b.type==="crystal"){G.fillStyle="#e9d5ff";G.font="18px serif";G.textAlign="center";G.fillText("◆",b.x+b.w/2,b.y+29)}if(b.type==="explosive"){G.fillStyle="#ffe4e6";G.font="18px serif";G.textAlign="center";G.fillText("✹",b.x+b.w/2,b.y+29)}if(b.hp>1&&b.type!=="crystal"){G.fillStyle="#fff";G.font="bold 13px sans-serif";G.textAlign="center";G.fillText(b.hp,b.x+b.w/2,b.y+27)}});
if(boss){let gr=G.createLinearGradient(boss.x,boss.y,boss.x+boss.w,boss.y);gr.addColorStop(0,"#3b1b68");gr.addColorStop(.5,"#8b3db3");gr.addColorStop(1,"#3b1b68");G.shadowBlur=35;G.shadowColor="#d946ef";G.fillStyle=gr;roundRect(boss.x,boss.y,boss.w,boss.h,30);G.shadowBlur=0;G.strokeStyle="#f0abfc";G.lineWidth=3;G.strokeRect(boss.x+15,boss.y+15,boss.w-30,boss.h-30);G.fillStyle="#f5d0fe";G.font="38px serif";G.textAlign="center";G.fillText("✦  ◇  ✦",boss.x+boss.w/2,boss.y+72)}
for(let b of balls){b.trail.forEach((q,i)=>{G.globalAlpha=(i/b.trail.length)*.25;G.fillStyle=active.fire>t?"#fb923c":"#67e8f9";G.beginPath();G.arc(q.x,q.y,b.r*(i/b.trail.length),0,7);G.fill()});G.globalAlpha=1;G.shadowBlur=28;G.shadowColor=active.fire>t?"#f97316":"#22d3ee";let orb=G.createRadialGradient(b.x-3,b.y-3,1,b.x,b.y,b.r);orb.addColorStop(0,"#fff");orb.addColorStop(.45,active.fire>t?"#fed7aa":"#cffafe");orb.addColorStop(1,active.fire>t?"#f97316":"#0891b2");G.fillStyle=orb;G.beginPath();G.arc(b.x,b.y,b.r,0,7);G.fill();G.shadowBlur=0}
G.shadowBlur=25;G.shadowColor="#22d3ee";let pg=G.createLinearGradient(paddle.x,0,paddle.x+paddle.w,0);pg.addColorStop(0,"#16b7cf");pg.addColorStop(.5,"#effcff");pg.addColorStop(1,"#7c3aed");G.fillStyle=pg;roundRect(paddle.x,paddle.y,paddle.w,paddle.h,14);G.shadowBlur=0;G.fillStyle="#fff8";roundRect(paddle.x+12,paddle.y+4,paddle.w-24,5,3);
const glyph={wide:"↔",multi:"×3",laser:"ϟ",slow:"◷",shield:"◇",fire:"✹",magnet:"∩",bomb:"✺",life:"+1"};drops.forEach(d=>{G.save();G.translate(d.x,d.y);G.rotate(Math.sin(d.spin)*.15);G.shadowBlur=20;G.shadowColor="#fbbf24";G.fillStyle="#0c1628";G.strokeStyle="#ffd166";G.lineWidth=3;G.beginPath();G.arc(0,0,23,0,7);G.fill();G.stroke();G.shadowBlur=0;G.fillStyle="#fff";G.font="bold 14px sans-serif";G.textAlign="center";G.fillText(glyph[d.type],0,5);G.restore()});
G.strokeStyle="#fb7185";G.shadowBlur=12;G.shadowColor="#fb7185";G.lineWidth=5;shots.forEach(s=>{G.beginPath();G.moveTo(s.x,s.y);G.lineTo(s.x,s.y+24);G.stroke()});G.shadowBlur=0;
parts.forEach(p=>{G.globalAlpha=Math.max(0,p.life);G.fillStyle=p.col;G.fillRect(p.x,p.y,p.size,p.size)});G.globalAlpha=1;
if(balls.some(b=>b.stuck)&&state==="play"){G.fillStyle="#dbeafeaa";G.font="800 19px sans-serif";G.textAlign="center";G.fillText(active.magnet>t?"TAP TO RELEASE ORB":"TAP / SPACE TO LAUNCH",W/2,1195)}
if(flash>0){G.globalAlpha=flash;G.fillStyle="#fff";G.fillRect(0,0,W,H);G.globalAlpha=1;flash=Math.max(0,flash-.08)}
G.restore()}
function loop(t){let dt=Math.min(.025,(t-last)/1000||0);last=t;step(dt,t);draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function showGame(){document.querySelectorAll(".overlay").forEach(x=>x.classList.remove("show"));newRun();state="play"}
$("#play").onclick=showGame;$("#again").onclick=showGame;function pause(){if(state==="play"){state="pause";$("#pause").classList.add("show")}else if(state==="pause"){state="play";$("#pause").classList.remove("show")}}$("#pauseBtn").onclick=pause;$("#resume").onclick=pause;$("#restart").onclick=()=>{loadStage();$("#pause").classList.remove("show");state="play"};
function modal(kind){let c=$("#modalContent");if(kind==="how")c.innerHTML='<h2>HOW TO PLAY</h2><div class="how"><p><b>Angle matters.</b> Hit different parts of the paddle to steer the orb.</p><p><b>Combo</b> grows while you keep breaking bricks. Paddle contact does not erase it; inactivity does.</p><p><b>Runes:</b> ↔ Wide · ×3 Trinity · ϟ Laser · ◷ Chrono · ◇ Aegis · ✹ Inferno · ∩ Magnet · ✺ Nova · +1 Life.</p><p><b>Special bricks:</b> Crystal has extra health, Steel is heavily armored, Nova bricks explode into neighbors. Every fifth stage contains a boss.</p><p>Magnet catches the orb on the paddle; tap again to release. Aegis saves one missed volley.</p></div>';else c.innerHTML='<h2>SETTINGS</h2>'+["sound","particles","shake"].map(k=>`<label class="setting"><span>${k.toUpperCase()}</span><input type="checkbox" data-set="${k}" ${cfg[k]?"checked":""}></label>`).join("")+'<p>Best score and settings save automatically on this device.</p>';$("#modal").classList.add("show");c.querySelectorAll("[data-set]").forEach(i=>i.onchange=()=>{cfg[i.dataset.set]=i.checked;saveGame()})}
$("#how").onclick=()=>modal("how");$("#settings").onclick=()=>modal("settings");document.querySelectorAll(".settingsOpen").forEach(b=>b.onclick=()=>modal("settings"));$("#closeModal").onclick=()=>$("#modal").classList.remove("show");
addEventListener("keydown",e=>{keys[e.key]=true;if(e.key===" "){e.preventDefault();launch()}if((e.key.toLowerCase()==="p"||e.key==="Escape")&&!$("#modal").classList.contains("show"))pause()});addEventListener("keyup",e=>keys[e.key]=false);
function px(e){let r=C.getBoundingClientRect();return(e.clientX-r.left)/r.width*W}C.addEventListener("pointermove",e=>{if(state==="play")paddle.target=px(e)-paddle.w/2});C.addEventListener("pointerdown",e=>{if(state==="play"){paddle.target=px(e)-paddle.w/2;launch()}});
E.best.textContent=best.toLocaleString();hud();
})();